server.port: 9070

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

springdoc:
  default-consumes-media:type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true

logging:
  level.org.springframework.security: DEBUG
