/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '15. 7. 18 오후 11:03' with Gradle 2.3
 *
 * @author Administrator, @date 15. 7. 18 오후 11:03
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
