/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yun_dev1' at '16. 7. 13 오후 5:25' with Gradle 2.13
 *
 * @author yun_dev1, @date 16. 7. 13 오후 5:25
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
